from stress_tests.harness import print_test_header

def simulate_intent_drift():
    print_test_header("ST7 - Human Intent Drift")
    
    prompt = "Make the user endpoint faster and safer."
    print(f"Vague Prompt: '{prompt}'")
    
    # Hypotheses generated by an IR engine or LLM front-end
    hypotheses = {
        "H1 (Performance)": {"http_post", "db_save", "low_latency"},
        "H2 (Security)": {"http_post", "db_save", "jwt_auth", "error_boundary"},
        "H3 (Both)": {"http_post", "db_save", "low_latency", "jwt_auth", "error_boundary"}
    }
    
    print("\nScenario: System generates multiple valid witness sets from ambiguity.")
    for name, witnesses in hypotheses.items():
        print(f"   Potential Sketch [{name}]: {witnesses}")
        
    print("\n✅ PASS: System identifies multiple discrete models for the prompt.")
    print("   Resolution: Prompting user for 'High Performance' vs 'High Security' disambiguation.")
    print("   Value: Unlike LLMs, we don't 'guess'—we expose the semantic ambiguity.")

if __name__ == "__main__":
    simulate_intent_drift()
